/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class globalquake_jni_GQNativeFunctions */

#ifndef _Included_globalquake_jni_GQNativeFunctions
#define _Included_globalquake_jni_GQNativeFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     globalquake_jni_GQNativeFunctions
 * Method:    getTheUltimateAnswer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_globalquake_jni_GQNativeFunctions_getTheUltimateAnswer
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
